<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWindowsForms>true</UseWindowsForms>
		<UseWPF>true</UseWPF>
		<ApplicationIcon>logo.ico</ApplicationIcon>
		<PackageIcon>logo.ico</PackageIcon>
		<ApplicationManifest>app.manifest</ApplicationManifest>
	</PropertyGroup>

	<ItemGroup>
		<None Include="logo.ico">
		  <Pack>True</Pack>
		  <PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2592.51" />
	</ItemGroup>

	<ItemGroup>
		<None Update="effect.wav">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<Page Update="ImageViewerWindow.xaml">
			<Generator>MSBuild:Compile</Generator>
			<XamlRuntime>Wpf</XamlRuntime>
		</Page>
		<Page Update="GalleryWindow.xaml">
			<Generator>MSBuild:Compile</Generator>
			<XamlRuntime>Wpf</XamlRuntime>
		</Page>
		<Page Update="ClipboardSaverWindow.xaml">
			<Generator>MSBuild:Compile</Generator>
			<XamlRuntime>Wpf</XamlRuntime>
		</Page>
		<Page Update="InputRecorderWindow.xaml">
			<Generator>MSBuild:Compile</Generator>
			<XamlRuntime>Wpf</XamlRuntime>
		</Page>
	</ItemGroup>

</Project>
